# Generated by Django 5.1.1 on 2024-11-09 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='library_name',
        ),
        migrations.RemoveField(
            model_name='book',
            name='mms_id',
        ),
        migrations.RemoveField(
            model_name='book',
            name='process_type',
        ),
    ]
